### ISSUE TITLE
Deprecated templates

### ISSUE THREAD

**Issue by smohadjer** [biotope/biotope#16]
Is it possible to mark templates as "deprecated" so that on index page they are displayed with special styling, same as we had in previous versions of frontend framework? If so,  it's not being mentioned in readme.md

**Comment by janrembold** [comment]
You should be able to add any kind of property to your page templates YAML header. Everything in there is available in src/index.hbs. Just add a corresponding if-statement for your flag into that template. Currently you can use bootstrap default elements. But we are planning to refactor the index template and will remove the external bootstrap dependency soon

**Comment by smohadjer** [comment]
Thanks for the tip. I still think since deprecating templates is a relatively common task it would be useful if this feature is implemented in framework. This is how I added it in my project:

`<h4><a href="{{indexr.file.name}}.html">{{bioDef this.title indexr.file.name}}</a> {{#if this.deprecated}}<mark><em>deprecated</em></mark>{{/if}}</h4>`

**Comment by janrembold** [comment]
Agreed, could you please send a PR to the frontend repo? 
It would be good to mention this feature in https://github.com/biotope/frontend-framework/tree/master/src/pages

**Comment by smohadjer** [comment]
Here is the pr: https://github.com/biotope/frontend-framework/pull/17
