### ISSUE TITLE
Enable "Snyk" for Security Checks on all Repositories

### ISSUE THREAD

**Issue by davelosert** [biotope/biotope#18]
Snyk is a security checker for NPM Dependencies that could be used to identify security risks within the Biotope-Ecosystem.

It is free for open-source projects and could therefore be easily connected with all of biotopes repositories.

For more info see the website:
https://snyk.io/

Just a suggestion ;)

**Comment by timomayer** [comment]
hey @davelosert thanks for that :)
i have enabled snyk and snyk checks for all biotope repos :)
