### ISSUE TITLE
Yarn start does not work on windows

### ISSUE THREAD

**Issue by markuspl** [biotope/biotope#25]
On windows yarn start does not work and exit with an error.

```
C:\dev\frontend-turbo-diesel\node_modules\.bin\gulp:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

Which is granted under scripts in the package.json

Problem occures because the given path "node node_modules/.bin/gulp" selects a file which is not processable with windows.

Quickfix: Change path to "node node_modules/gulp/bin/gulp"

We need to discuss if this a valid solution or if we need some better solution.

**Comment by timomayer** [comment]
@SheepFromHeaven  @janrembold think Markus fix will break Mac OSX can you confirm that?

**Comment by janrembold** [comment]
Yes, this will break the execution under OSX.

But I think it isn't necessary to use the local node modules path anyway. All scripts started by yarn/npm already have this folder in their "PATH". 

@markuspl Please try to rename your scripts to:
```
"mocha": "mocha",
"gulp": "gulp",

"serve:gulp": "gulp serve",
"build:gulp": "gulp build",
```

**Comment by timomayer** [comment]
Thanks @janrembold. If that works please send a PR @markuspl :)

**Comment by janrembold** [comment]
As an addition, I still don't know why we need wrappers for those functions:
```
    "serve:gulp": "npm run gulp serve",
    "build:gulp": "npm run gulp build",

    "start": "npm run serve:gulp",
    "build": "npm run build:gulp",
```

For me it would be enough to have only `start` and `build` scripts that really don't need this npm dependency. Running `yarn start` that results in `gulp serve` works perfectly fine in my environment where I don't have a global gulp installed.
