### ISSUE TITLE
Update bio-helpers documentation

### ISSUE THREAD

**Issue by janrembold** [biotope/biotope#28]
The bio-prefixed handlebars helpers are not up to date. See https://github.com/biotope/biotope-build/blob/master/lib/hbs-helpers.js for current list of helpers and update readme.md in this project

**Comment by alxbenz** [comment]
The helpers have moved: https://github.com/biotope/biotope-build/blob/master/lib/hb2-helpers.js

**Comment by SheepFromHeaven** [comment]
Closed in the new repo: https://github.com/biotope/biotope-build/blob/master/lib/hb2-helpers.js
