### ISSUE TITLE
CDN and local version of jQuery in use

### ISSUE THREAD

**Issue by iam-robin** [biotope/biotope#36]
Currently jQuery is included in two different ways:

- loaded from CDN (index.hbs, browserSupport.hbs)
- local jQuery module (included in every layout/page)

**Comment by timomayer** [comment]
hi robin. thanks for the issue but thats ok like it is.
indexer and browserSupport page are pages coming out of biotope while all other things are the things build with biotope. Customer projects should not rely on a jQuery version of biotope.

**Comment by SheepFromHeaven** [comment]
@timomayer that's right, but the other way arount should work. Currently you cannot develop in a preinstalled biotope instance locally. Right?

**Comment by SheepFromHeaven** [comment]
Referencing to #33

**Comment by timomayer** [comment]
@SheepFromHeaven thats why we have the "offline" ticket you created. i agree we have to solve that, but it should be still two seperated jquery versions
