### ISSUE TITLE
Update the patterns section of the readme

### ISSUE THREAD

**Issue by luke-m** [biotope/biotope#39]
The local typescript demos `src/resources/ts/jquery.plugin.advanced.ts` and `src/resources/ts/jquery.plugin.simple.ts` referenced in the README file ('Patterns' section) do not exist. 
Also, the jQuery section references the wrong file (`/patterns/jquery.typescript.boilerplate.ts`)
Does this whole section need to be updated?

**Comment by SheepFromHeaven** [comment]
Merged
